### ISSUE TITLE
Add setting re-publication (readback) support

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/miniconf#10]
~Add support for reading back a staged settings value~

Add support for publishing active settings. Those settings may differ from the MQTT view for several reasons:

* Rounding due to value conversion (e.g. DDS FTW words)
* Custom validation hooks, value boundaries
* Application changes
* No data in MQTT available yet (because it was never set)

**Comment by jordens** [comment]
I'm not sure pull readback would be a prime usecase. It would be better to generally ensure that the MQTT view of the active settings is consistent with the device reality. In that sense the solution would be to publish the settings when they are activated. That also addresses:

* Making the active settings available in MQTT when the device boots and there are no retained settings
* Publishing settings changes due to firmware changes
* Validation/implicit rejection of the settings from the staged ones on commit
* Possible interdependencies of settings (the range of one value depending on another).
* Pivoting to the configured settings tree (#25)

**Comment by ryan-summers** [comment]
To update, the primary use case here is to publish the default, power-on active settings if no data is received over the MQTT interface so that the active configuration is available via the broker. Settings should be published back to the topic that is used to configure them in the first place.
